class AppIcons {
  const AppIcons._();
  static const String path = 'assets/images';
  static const String avatarka = '$path/profile_avatar.png';
  static const String drawer_edit = '$path/drawer_edit.png';
  static const String drawer_search = '$path/drawer_search.png';
  static const String drawer_wallet = '$path/drawer_wallet.png';
  static const String play = '$path/playR.png';
  static const String next = '$path/next.png';
  static const String play_white = '$path/play_white.png';
  static const String pause_white = '$path/pause_white.png';
  static const String play_aud = '$path/play_aud.png';
  static const String rec_delete = '$path/rec_delete.png';
  static const String rec_paper_download = '$path/rec_paper_download.png';
  static const String rec_upload = '$path/rec_upload.png';
  static const String stop = '$path/stop.png';
  static const String tabbar_category = '$path/tabbar_category.png';
  static const String tabbar_componen = '$path/tabbar_componen.png';
  static const String tabbar_home = '$path/tabbar_home.png';
  static const String tabbar_paper = '$path/tabbar_paper.png';
  static const String tabbar_profile = '$path/tabbar_profile.png';
  static const String vector = '$path/vector.png';
  static const String camera = '$path/сamera.png';
  static const String microfon = '$path/microfon.png';
  static const String heart = '$path/heart.png';
  static const String search = '$path/search.png';
  static const String play_podborki = '$path/play_podborki.png';
  static const String stop_podborki = '$path/stop_podborki.png';
  static const String tick = '$path/tick.png';
  static const String subscription_upload = '$path/subscription_upload.png';
  static const String subscription_infinity = '$path/subscription_infinity.png';
  static const String subscription_download = '$path/subscription_download.png';
  static const String delete = '$path/delete.png';
}
